# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EventMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
    name='EventMessage.proto',
    package='',
    serialized_pb='\n\x12\x45ventMessage.proto\"\x91\x01\n\x05\x45vent\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x12\n\nevent_type\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x1a\n\x05pairs\x18\x05 \x03(\x0b\x32\x0b.Event.Pair\x1a\"\n\x04Pair\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\")\n\x14TimestampSyncRequest\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\"%\n\x15TimestampSyncResponse\x12\x0c\n\x04\x64iff\x18\x01 \x02(\x03\"+\n\x11\x42\x61tchEventRequest\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.EventB\x1b\n\x19\x65u.nordeus.tracking.proto')

_EVENT_PAIR = _descriptor.Descriptor(
    name='Pair',
    full_name='Event.Pair',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='Event.Pair.key', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='value', full_name='Event.Pair.value', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=134,
    serialized_end=168,
)

_EVENT = _descriptor.Descriptor(
    name='Event',
    full_name='Event',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='user_id', full_name='Event.user_id', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='event_id', full_name='Event.event_id', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='event_type', full_name='Event.event_type', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='Event.timestamp', index=3,
            number=4, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='pairs', full_name='Event.pairs', index=4,
            number=5, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[_EVENT_PAIR, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=23,
    serialized_end=168,
)

_TIMESTAMPSYNCREQUEST = _descriptor.Descriptor(
    name='TimestampSyncRequest',
    full_name='TimestampSyncRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='TimestampSyncRequest.timestamp', index=0,
            number=1, type=3, cpp_type=2, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=170,
    serialized_end=211,
)

_TIMESTAMPSYNCRESPONSE = _descriptor.Descriptor(
    name='TimestampSyncResponse',
    full_name='TimestampSyncResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='diff', full_name='TimestampSyncResponse.diff', index=0,
            number=1, type=3, cpp_type=2, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=213,
    serialized_end=250,
)

_BATCHEVENTREQUEST = _descriptor.Descriptor(
    name='BatchEventRequest',
    full_name='BatchEventRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='events', full_name='BatchEventRequest.events', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=252,
    serialized_end=295,
)

_EVENT_PAIR.containing_type = _EVENT;
_EVENT.fields_by_name['pairs'].message_type = _EVENT_PAIR
_BATCHEVENTREQUEST.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['TimestampSyncRequest'] = _TIMESTAMPSYNCREQUEST
DESCRIPTOR.message_types_by_name['TimestampSyncResponse'] = _TIMESTAMPSYNCRESPONSE
DESCRIPTOR.message_types_by_name['BatchEventRequest'] = _BATCHEVENTREQUEST


class Event(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType

    class Pair(_message.Message):
        __metaclass__ = _reflection.GeneratedProtocolMessageType
        DESCRIPTOR = _EVENT_PAIR

        # @@protoc_insertion_point(class_scope:Event.Pair)

    DESCRIPTOR = _EVENT

    # @@protoc_insertion_point(class_scope:Event)


class TimestampSyncRequest(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TIMESTAMPSYNCREQUEST

    # @@protoc_insertion_point(class_scope:TimestampSyncRequest)


class TimestampSyncResponse(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TIMESTAMPSYNCRESPONSE

    # @@protoc_insertion_point(class_scope:TimestampSyncResponse)


class BatchEventRequest(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BATCHEVENTREQUEST

    # @@protoc_insertion_point(class_scope:BatchEventRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\031eu.nordeus.tracking.proto')
# @@protoc_insertion_point(module_scope)
