# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PushNotificationMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
    name='PushNotificationMessage.proto',
    package='',
    serialized_pb='\n\x1dPushNotificationMessage.proto\"T\n\x10PushNotification\x12\x10\n\x08login_id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0e\n\x06screen\x18\x04 \x01(\t\"D\n\x18\x42\x61tchNotificationRequest\x12(\n\rnotifications\x18\x01 \x03(\x0b\x32\x11.PushNotificationB\x1b\n\x19\x65u.nordeus.tracking.proto')

_PUSHNOTIFICATION = _descriptor.Descriptor(
    name='PushNotification',
    full_name='PushNotification',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='login_id', full_name='PushNotification.login_id', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='title', full_name='PushNotification.title', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='content', full_name='PushNotification.content', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='screen', full_name='PushNotification.screen', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=unicode("", "utf-8"),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=33,
    serialized_end=117,
)

_BATCHNOTIFICATIONREQUEST = _descriptor.Descriptor(
    name='BatchNotificationRequest',
    full_name='BatchNotificationRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='notifications', full_name='BatchNotificationRequest.notifications', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    serialized_start=119,
    serialized_end=187,
)

_BATCHNOTIFICATIONREQUEST.fields_by_name['notifications'].message_type = _PUSHNOTIFICATION
DESCRIPTOR.message_types_by_name['PushNotification'] = _PUSHNOTIFICATION
DESCRIPTOR.message_types_by_name['BatchNotificationRequest'] = _BATCHNOTIFICATIONREQUEST


class PushNotification(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PUSHNOTIFICATION

    # @@protoc_insertion_point(class_scope:PushNotification)


class BatchNotificationRequest(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BATCHNOTIFICATIONREQUEST

    # @@protoc_insertion_point(class_scope:BatchNotificationRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\031eu.nordeus.tracking.proto')
# @@protoc_insertion_point(module_scope)
